### 프로세스
```
1) 문제 정의 및 가설 설정하기
2) 데이터 분석 기본 세팅 하기
3) 데이터 분석하기
4) 분석 결과 시각화 하기
5) 최종 결론 내리기
```

### 데이터 분류
```
1. 사용자의 학습 활동 패턴
-각 학습 세션에 소요된 평균 시간
-월간 활동적인 학습 일수
-완료한 총 코스 수
-최근 학습 성취도
-중단된 학습 세션 수

2. 서비스 이용 패턴
-사용자가 서비스에 가입한 기간 (월)
-사용자가 마지막으로 로그인한 시간 (일)
-사용자의 일반적인 로그인 시간

3. 결제 패턴
-구독 유형
-payment 패턴

4. 콘텐츠에 대한 반응 
-커뮤니티 참여도
-선호하는 난이도

5. 기타
-고객 문의 이력
-타켓 여부
```

In [ ]:
# 데이터 뜯어보기

In [2]:
import pandas as pd

In [24]:
df1 = pd.read_csv('./data/mini.csv')
df1

,user_id,subscription_duration,recent_login_time,average_login_time,average_time_per_learning_session,monthly_active_learning_days,total_completed_courses,recent_learning_achievement,abandoned_learning_sessions,community_engagement_level,preferred_difficulty_level,subscription_type,customer_inquiry_history,payment_pattern,target
0,b919c29d,13,14,14.946163,8.427187,18,16,68.360455,3,4,Low,Basic,4,5,0
1,a0a60abb,16,18,18.453224,72.646087,16,13,97.567322,2,3,Medium,Basic,1,6,1
2,b9f171ae,22,1,16.195228,21.774492,13,14,94.358763,3,4,Medium,Premium,0,7,1
3,5dc0ba8b,1,19,17.628656,42.659066,19,18,70.153228,0,3,Low,Basic,1,0,1
4,65c83654,4,5,21.390656,30.744287,19,10,81.917908,2,4,Medium,Basic,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ae6b76bc,22,29,14.727623,84.053558,18,16,64.966803,2,5,Low,Premium,1,1,1
9996,24588752,10,11,19.374054,45.464833,9,8,82.750244,3,3,Medium,Basic,2,7,1
9997,e4622a54,7,27,18.240978,127.302411,24,14,81.567839,3,5,High,Basic,1,6,1
9998,e07fbad9,11,7,18.783800,5.297234,10,10,89.885656,4,5,Low,Basic,2,0,1
9999,e12dcb55,10,5,13.073230,28.120031,3,13,64.811297,4,5,Low,Premium,0,3,0

In [26]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   user_id                            10000 non-null  object
 1   subscription_duration              10000 non-null  int64
 2   recent_login_time                  10000 non-null  int64
 3   average_login_time                 10000 non-null  float64
 4   average_time_per_learning_session  10000 non-null  float64
 5   monthly_active_learning_days       10000 non-null  int64
 6   total_completed_courses            10000 non-null  int64
 7   recent_learning_achievement        10000 non-null  float64
 8   abandoned_learning_sessions        10000 non-null  int64
 9   community_engagement_level         10000 non-null  int64
 10  preferred_difficulty_level         10000 non-null  object
 11  subscription_type                  10000 non-null  object
 12  customer_inquiry_history           10000 non-null  int64
 13  payment_pattern                    10000 non-null  int64
 14  target                             10000 non-null  int64
dtypes: float64(3), int64(9), object(3)
memory usage: 1.1+ MB

In [28]:
df1.describe()

,subscription_duration,recent_login_time,average_login_time,average_time_per_learning_session,monthly_active_learning_days,total_completed_courses,recent_learning_achievement,abandoned_learning_sessions,community_engagement_level,customer_inquiry_history,payment_pattern,target
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,11.897400,15.013200,14.994076,54.917720,12.545400,12.227500,75.029513,3.043600,3.886100,2.010500,3.502900,0.619900
std,6.600896,8.362573,3.001869,56.024310,6.932239,3.634125,9.968529,1.755052,1.262175,1.420983,2.311261,0.485435
min,1.000000,1.000000,2.366189,0.011515,1.000000,1.000000,35.941755,0.000000,1.000000,0.000000,0.000000,0.000000
25%,6.000000,8.000000,13.025597,15.276611,7.000000,10.000000,68.278054,2.000000,3.000000,1.000000,1.000000,0.000000
50%,12.000000,15.000000,14.979228,37.578818,13.000000,12.000000,75.126061,3.000000,4.000000,2.000000,4.000000,1.000000
75%,18.000000,22.000000,16.995340,75.584200,19.000000,15.000000,81.718976,4.000000,5.000000,3.000000,6.000000,1.000000
max,23.000000,29.000000,26.998490,503.372616,24.000000,27.000000,112.643828,12.000000,5.000000,10.000000,7.000000,1.000000

In [22]:
df2 = pd.read_csv('./data/user_data.csv')
df2

,_id,created_at,updated_at,name,marketing,managed,gender,age,progress_rate
0,e88cbf158991b41c,2022-08-26 10:04:54,2022-10-07 8:35:47,온아린,False,True,male,10,100.00
1,34525c4c113ea233,2021-02-20 1:23:38,2022-08-08 22:04:00,유강민,False,False,female,40,63.64
2,8f869d1ce7289b3d,2021-02-20 1:23:38,2022-08-08 22:04:00,문민서,False,False,female,30,63.64
3,bf1e94f981743e8d,2022-07-22 15:59:44,2022-08-29 21:12:15,석준영,False,False,male,50,64.77
4,b281c6fc121a338c,2022-07-22 15:59:44,2022-08-29 21:12:15,석도현,False,False,male,20,64.77
...,...,...,...,...,...,...,...,...,...
2569,17cb6b9a82c3551f,2022-06-29 19:15:40,2022-07-28 16:17:12,설현우,True,True,male,40,0.00
2570,567b4a345638d73c,2022-03-09 11:19:45,2022-07-25 9:49:32,최도훈,True,True,female,10,0.00
2571,448eacf2512feca9,2022-08-06 10:38:01,2022-08-22 18:40:04,신지완,True,True,female,30,0.00
2572,4cfec575328d88a2,2022-08-06 10:38:01,2022-08-22 18:40:04,곽소희,True,True,female,30,0.00
2573,9ccc777229729491,2022-09-16 16:17:13,2022-10-03 20:48:45,공하준,True,True,male,30,98.86

In [ ]:
# 요구사항 분석
독자들 중 누가 서비스 구독을 연장할지 예측하기 위한 사전 파악